name: Check Pull Request

on: pull_request

jobs:    
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set-up front-end dependencies
        run: |
          # Navigate to theme folder
          cd wp-content/themes/lavandre
          
          # Install dependencies
          npx yarn
          
          # Run JS unit tests
          npx jest --silent
      
